In [1]:

import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tflearn.layers.core import input_data, fully_connected
from tflearn.layers.estimator import regression
import tflearn
import numpy as np
from tflearn.metrics import Accuracy

WARNING:tensorflow:From C:\Users\dokee\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\compat\v2_compat.py:101: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
curses is not supported on this machine (please install/reinstall curses for an optimal experience)

In [2]:
selected_df = pd.read_csv("HR1_10SCALE_encoded.csv")
#selected_df = selected_df.drop("Unnamed: 0",axis=1)
ide = selected_df["HR1_10SCALE"].copy()
selected_df = selected_df.drop("HR1_10SCALE",axis=1)
for index, values in selected_df.iteritems():
    selected_df[index] = values / values.max()
selected_df["HR1_10SCALE"] = ide
selected_df

<ipython-input-2-b679a025227a>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  selected_df["HR1_10SCALE"] = ide

,Unnamed: 0,age,STIMULUS5_A,STIMULUS5_D,STIMULUS5_E,STIMULUS5_C,STIMULUS5_B,STIMULUS5_F,DEMOGRAPHIC5_46825,DEMOGRAPHIC5_81650,...,DEMOGRAPHIC5_31323,DEMOGRAPHIC5_90005,DEMOGRAPHIC5_18051,DEMOGRAPHIC5_25271,DEMOGRAPHIC5_43701,DEMOGRAPHIC5_34475,DEMOGRAPHIC5_6152,DEMOGRAPHIC5_21740,DEMOGRAPHIC5_40353,HR1_10SCALE
0,0.000000,0.311688,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
1,0.000826,0.298701,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
2,0.001653,0.350649,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10
3,0.002479,0.662338,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
4,0.003306,0.480519,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1206,0.996694,0.285714,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,5
1207,0.997521,0.311688,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1
1208,0.998347,0.259740,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4
1209,0.999174,0.623377,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1
1210,1.000000,0.883117,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5

In [3]:
selected_df["HR1_10SCALE"].unique()

array([ 4, 10,  5,  1,  3,  7,  2,  8,  6,  9], dtype=int64)

In [4]:
encod = [[0,0,0,0,0,0,0,0,0],
        [1,0,0,0,0,0,0,0,0],
        [1,1,0,0,0,0,0,0,0],
        [1,1,1,0,0,0,0,0,0],
        [1,1,1,1,0,0,0,0,0],
        [1,1,1,1,1,0,0,0,0],
        [1,1,1,1,1,1,0,0,0],
        [1,1,1,1,1,1,1,0,0],
        [1,1,1,1,1,1,1,1,0],
        [1,1,1,1,1,1,1,1,1]]
tmp = []
values = [1,2,3,4,5,6,7,8,9,10]
for i in selected_df["HR1_10SCALE"].tolist():
    tmp.append(encod[values.index(i)])
selected_df["HR1_10SCALE"] = tmp
selected_df["HR1_10SCALE"].tolist()[0]

[1, 1, 1, 0, 0, 0, 0, 0, 0]

In [5]:
X = selected_df.drop("HR1_10SCALE",axis=1)
y = selected_df["HR1_10SCALE"]
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size = .75, test_size = .25, random_state = 72)

In [6]:
x_train.shape

(908, 949)

In [7]:

x_train = np.array(x_train.drop("Unnamed: 0",axis=1))
x_test = np.array(x_test.drop("Unnamed: 0",axis=1))
x_train

array([[0.38961039, 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.32467532, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.4025974 , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.58441558, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.66233766, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.45454545, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [8]:
out = np.array(y_train, dtype=object)
out = out.tolist()
out_test = np.array(y_test, dtype=object)
out_test = out_test.tolist()

In [9]:

tf.compat.v1.reset_default_graph()
acc = Accuracy()
model = input_data(shape=(None,948), name='input') # This basically just specifies the shape of input
model = fully_connected(model, 25, activation='relu')
model = fully_connected(model,9, activation='sigmoid')
model = regression(model, optimizer='adam', learning_rate=1e-2, loss='categorical_crossentropy',metric = acc, name='target')
model = tflearn.DNN(model, tensorboard_dir="log")
# x_train = np.array([i[0] for i in x_train]).reshape(-1, 908, 996)
# y_train = np.array([i[1] for i in y_train]).reshape(-1, 1)
#out = np.empty_like(y_train, dtype=object)
model.fit(x_train,out, n_epoch = 50, validation_set=(x_test,out_test), shuffle = True, run_id = 'AlphaSnake.tflearn')
#model.evaluate(x_train, np.array(out))
#model.fit(x_train,y_train, n_epoch = 3, shuffle = True, run_id = 'AlphaSnake.tflearn')
#model.save('AlphaSnake.tflearn')
# x_test1 = np.array(x_test.drop("Unnamed: 0",axis=1
# model.predict(x_test1)

Training Step: 749  | total loss: 7.04970 | time: 0.058s
| Adam | epoch: 050 | loss: 7.04970 -- iter: 896/908
Training Step: 750  | total loss: 7.12278 | time: 1.071s
| Adam | epoch: 050 | loss: 7.12278 | val_loss: 8.21657 -- iter: 908/908
--

In [10]:
out = np.array(y_test, dtype=object)
out = out.tolist()
model.evaluate(x_test,np.array(out_test))

[0.8910891120583311]

In [11]:
model.save('AlphaSnake.tflearn')

INFO:tensorflow:C:\Notebooks\DS\ReformedAI\AlphaSnake.tflearn is not in all_model_checkpoint_paths. Manually adding it.