## Working on encoding our data

In [1]:
import pandas as pd
import numpy as np

In [2]:
cleaned_df = pd.read_csv("step2_cleaned_df.csv")

In [3]:
cleaned_df = cleaned_df.drop(["COVID_HR1","COVID_HR2","IDEOLOGY4"],axis=1)
missing = ["HR11","IDEOLOGY7","DEMOGRAPHIC1"]
for i in missing:
    mode = cleaned_df[i].mode()
    print(mode[0])
    fixed = []
    for value in cleaned_df[i]:
        if value != value:
            fixed.append(mode[0])
        else:
            fixed.append(value)
    cleaned_df[i] = fixed

B
C
retired

In [4]:
np.unique(np.array(cleaned_df["HR11"].to_list()))

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [5]:
cleaned_df["HR8"]

0       2
1       2
2       0
3       1
4       0
       ..
1206    3
1207    3
1208    2
1209    3
1210    1
Name: HR8, Length: 1211, dtype: int64

In [6]:
for (columnName, columnData) in cleaned_df.iteritems(): 
    missingCount = columnData.isnull().sum() 
    percentage = (missingCount/len(cleaned_df))*100 
    #print(percentage)
    if missingCount > 0:        
        print("Missing Values in column : ", columnName, ", missing rows: ", 
            missingCount, ", missing percentage: ",  percentage, '%') 
        if percentage > 50.0:
            too_many_missing_value_columns.append(columnName)

### Encoding

In [7]:
nominal_df = cleaned_df[cleaned_df.select_dtypes(include=['object']).columns]

In [8]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
encoding_df = pd.DataFrame(columns=["Name","Values","Encoded Values"])
nn_df = pd.DataFrame()
print(nn_df)
#pd.unique(nominal_df["HR1_10SCALE"]).tolist()

names = []
values = []
evalues = []

for i in nominal_df.columns:
    unique = pd.unique(cleaned_df[i])
    count = 0
    if len(unique) < 10:
        for j in unique:
            name = i + str(count)
            tmp = []
            for k in nominal_df[i]:
                if k == j:
                    tmp.append(1)
                else:
                    tmp.append(0)
            count +=1
            nn_df[name] = tmp
nn_df

Empty DataFrame
Columns: []
Index: []

<ipython-input-8-587b120484c0>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  nn_df[name] = tmp

,HR110,HR111,HR112,HR113,HR130,HR131,HR132,HR133,HR134,HR135,...,DEMOGRAPHIC101,DEMOGRAPHIC102,DEMOGRAPHIC120,DEMOGRAPHIC121,DEMOGRAPHIC122,DEMOGRAPHIC123,DEMOGRAPHIC124,DEMOGRAPHIC125,DEMOGRAPHIC126,DEMOGRAPHIC127
0,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,1,0,0,0,1,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
2,0,0,1,0,0,0,1,0,0,0,...,1,0,1,0,0,0,0,0,0,0
3,0,0,1,0,1,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,1,0,0,...,1,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1206,1,0,0,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
1207,1,0,0,0,0,0,0,0,1,0,...,1,0,0,0,1,0,0,0,0,0
1208,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1209,1,0,0,0,0,0,0,0,1,0,...,1,0,0,0,1,0,0,0,0,0
1210,1,0,0,0,0,0,0,1,0,0,...,1,0,1,0,0,0,0,0,0,0

In [9]:
cleaned_df = cleaned_df.drop(nominal_df.columns,axis=1)
for index, value in nn_df.iteritems():
    cleaned_df[index] = value

<ipython-input-9-c48b2e9589da>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  cleaned_df[index] = value

In [10]:
cleaned_df

,Unnamed: 0,ARM,HR1_10SCALE,HR2_1,HR2_2,HR2_3,HR2_4,HR2_5,HR3,HR4,...,DEMOGRAPHIC101,DEMOGRAPHIC102,DEMOGRAPHIC120,DEMOGRAPHIC121,DEMOGRAPHIC122,DEMOGRAPHIC123,DEMOGRAPHIC124,DEMOGRAPHIC125,DEMOGRAPHIC126,DEMOGRAPHIC127
0,0,1,4,3,1,2,3,5,1,2,...,0,0,1,0,0,0,0,0,0,0
1,1,0,4,3,3,4,2,4,3,2,...,1,0,1,0,0,0,0,0,0,0
2,2,2,10,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
3,3,2,5,3,3,3,3,3,0,1,...,1,0,1,0,0,0,0,0,0,0
4,4,1,5,3,0,1,1,2,0,4,...,1,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1206,1206,0,5,1,2,2,5,1,3,4,...,1,0,0,0,1,0,0,0,0,0
1207,1207,0,1,5,5,4,4,5,4,4,...,1,0,0,0,1,0,0,0,0,0
1208,1208,0,4,4,4,5,5,4,3,3,...,0,0,1,0,0,0,0,0,0,0
1209,1209,0,1,5,5,5,5,5,4,4,...,1,0,0,0,1,0,0,0,0,0
1210,1210,1,5,2,2,2,2,2,3,1,...,1,0,1,0,0,0,0,0,0,0

Normalize

In [12]:
# for index, values in cleaned_df.iteritems():
#     cleaned_df[index] = cleaned_df[index] / cleaned_df[index].max()

In [13]:
cleaned_df

,Unnamed: 0,ARM,HR1_10SCALE,HR2_1,HR2_2,HR2_3,HR2_4,HR2_5,HR3,HR4,...,DEMOGRAPHIC101,DEMOGRAPHIC102,DEMOGRAPHIC120,DEMOGRAPHIC121,DEMOGRAPHIC122,DEMOGRAPHIC123,DEMOGRAPHIC124,DEMOGRAPHIC125,DEMOGRAPHIC126,DEMOGRAPHIC127
0,0.000000,0.5,0.4,0.6,0.2,0.4,0.6,1.0,0.25,0.50,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000826,0.0,0.4,0.6,0.6,0.8,0.4,0.8,0.75,0.50,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.001653,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.002479,1.0,0.5,0.6,0.6,0.6,0.6,0.6,0.00,0.25,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.003306,0.5,0.5,0.6,0.0,0.2,0.2,0.4,0.00,1.00,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1206,0.996694,0.0,0.5,0.2,0.4,0.4,1.0,0.2,0.75,1.00,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1207,0.997521,0.0,0.1,1.0,1.0,0.8,0.8,1.0,1.00,1.00,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1208,0.998347,0.0,0.4,0.8,0.8,1.0,1.0,0.8,0.75,0.75,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1209,0.999174,0.0,0.1,1.0,1.0,1.0,1.0,1.0,1.00,1.00,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1210,1.000000,0.5,0.5,0.4,0.4,0.4,0.4,0.4,0.75,0.25,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Chi Squared Feature Selection

for now we select features greater than 65

In [42]:
from matplotlib import pyplot
scores = []
selected_features = []
for i in range(len(fs.scores_)):
    #rint('Feature %s: %f' % (new_df.columns[i], fs.scores_[i]))
    scores.append(fs.scores_[i])
    if fs.scores_[i] > 65:
        selected_features.append(new_df.columns[i])
# plot the scores
# pyplot.bar([i for i in range(len(fs.scores_))], fs.scores_)
# pyplot.show()

In [47]:
new_df = cleaned_df.copy().drop("IDEOLOGY5",axis = 1)
from sklearn.model_selection import train_test_split
test = new_df.columns
target_feature = []
for i in test:
    if i == "HR8":
        target_feature.append(i)
X = new_df[selected_features] #obamacare
y = new_df["HR8"]
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size = .75, test_size = .25, random_state = 72)

In [21]:
test = (new_df < 0).any().to_list()
for i in range(len(new_df.columns)):
    if test[i]:
        print(new_df.columns[i])

In [22]:
from sklearn.feature_selection import SelectKBest, chi2
fs = SelectKBest(score_func=chi2, k='all')
fs.fit(x_train,y_train)
x_train_fs = fs.transform(x_train)
x_test_fs = fs.transform(x_test)

In [45]:
selected_features

['Unnamed: 0',
 'HR2_5',
 'HR6',
 'HR7_1',
 'HR7_2',
 'HR7_3',
 'HR7_4',
 'HR8',
 'HR12_1',
 'HR12_2',
 'STIMULUS3',
 'DEMOGRAPHIC13',
 'HR111',
 'HR147',
 'COVID_HR30']

In [41]:
tmp = np.array(scores)
tmp = np.sort(tmp[~np.isnan(tmp)])
tmp[-15:]

array([ 68.97834079,  71.11596754,  76.2555206 ,  80.20093606,
        80.58496521,  88.23857484, 103.02682682, 112.5472081 ,
       133.9492333 , 144.88445788, 150.4635697 , 170.12864986,
       187.70059265, 210.18614452, 328.11073875])

### Learning testing

In [28]:
pd.unique(y)

array([0.66666667, 0.        , 0.33333333, 1.        ])

In [48]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

In [49]:
clf = DecisionTreeClassifier(max_depth = 2)
print(y_train)
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print("Accuracy score:", metrics.accuracy_score(y_test,y_pred))
#cfm = pd.DataFrame(metrics.confusion_matrix(y_test,y_pred))
#print(cfm)

518     3
649     2
280     2
426     3
296     1
       ..
1031    1
837     1
1098    3
1070    1
472     3
Name: HR8, Length: 908, dtype: int64
Accuracy score: 0.9273927392739274

In [34]:
len(x_test.columns)
#inputshape = 1593,1

1593

In [50]:
import tensorflow as tf

In [19]:
x_train.to_csv("test.csv")

In [53]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units = 128, activation = 'relu', input_shape = (None, 15)))

In [54]:
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(units = 4, activation = 'softmax'))
model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['sparse_categorical_accuracy'])
model.fit(x_train, y_train, epochs =5)

Epoch 1/5
WARNING:tensorflow:Model was constructed with shape (None, None, 15) for input KerasTensor(type_spec=TensorSpec(shape=(None, None, 15), dtype=tf.float32, name='dense_2_input'), name='dense_2_input', description="created by layer 'dense_2_input'"), but it was called on an input with incompatible shape (None, 15).
WARNING:tensorflow:Model was constructed with shape (None, None, 15) for input KerasTensor(type_spec=TensorSpec(shape=(None, None, 15), dtype=tf.float32, name='dense_2_input'), name='dense_2_input', description="created by layer 'dense_2_input'"), but it was called on an input with incompatible shape (None, 15).
29/29 [==============================] - 0s 890us/step - loss: 40.4020 - sparse_categorical_accuracy: 0.2952
Epoch 2/5
29/29 [==============================] - 0s 926us/step - loss: 29.1330 - sparse_categorical_accuracy: 0.3029
Epoch 3/5
29/29 [==============================] - 0s 925us/step - loss: 27.7751 - sparse_categorical_accuracy: 0.3205
Epoch 4/5
29/29 [==============================] - 0s 890us/step - loss: 24.9675 - sparse_categorical_accuracy: 0.3139
Epoch 5/5
29/29 [==============================] - 0s 925us/step - loss: 23.0726 - sparse_categorical_accuracy: 0.3249

In [55]:
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(test_accuracy)

WARNING:tensorflow:Model was constructed with shape (None, None, 15) for input KerasTensor(type_spec=TensorSpec(shape=(None, None, 15), dtype=tf.float32, name='dense_2_input'), name='dense_2_input', description="created by layer 'dense_2_input'"), but it was called on an input with incompatible shape (None, 15).
10/10 [==============================] - 0s 774us/step - loss: 5.3565 - sparse_categorical_accuracy: 0.3762
0.3762376308441162

In [57]:
y_train.unique()

array([3, 2, 1, 0], dtype=int64)